spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/accounts
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      '[hibernate.dialect]': org.hibernate.dialect.PostgreSQLDialect
app:
  build:
    version: "1.0.1"
    java: "8"